version: "2"

linters:
  enable:
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - misspell
run:
  timeout: 5m

