version: "2"

linters:
  enable:
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - bodyclose
    - gocritic
    - gomodguard
    - whitespace

run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags:
    - integration
  issues-exit-code: 1
  tests: false

