logger:
  mod: ${LOGGER_MOD}

cache:
  default_exp_time: ${CACHE_DEFAULT_EXP_TIME}

server:
  http_port: ${SERVER_HTTP_PORT}
  shutdown_timeout: ${SERVER_SHUTDOWN_TIMEOUT}
  http_read_timeout: ${SERVER_HTTP_READ_TIMEOUT}
  http_write_timeout: ${SERVER_HTTP_WRITE_TIMEOUT}
  http_idle_timeout: ${SERVER_HTTP_IDLE_TIMEOUT}
  http_read_header_timeout: ${SERVER_HTTP_READ_HEADER_TIMEOUT}

postgres:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DATABASE}

kafka:
  brokers: ${KAFKA_BROKERS_URL}
  topics:
    input: ${KAFKA_INPUT_TOPIC}
  consumer:
    auto_offset_reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET}
    group_id: ${KAFKA_CONSUMER_GROUP_ID}

